site_name: busreservation
site_description: This is a REST application to manage the routes, drivers, and passangers in a bus agency.
repo_url: https://github.com/rafasis1986/bus-reservation
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/rafasis1986</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
