# Generated by Django 2.1.7 on 2019-03-08 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Trip'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='reservations.City'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='reservations.City'),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('bus', 'itinerary')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('trip', 'seat')},
        ),
        migrations.AlterUniqueTogether(
            name='itinerary',
            unique_together={('origin', 'destination', 'start')},
        ),
    ]
