# Generated by Django 2.1.7 on 2019-03-09 19:08

from django.db import migrations


def create_group_and_permissions(apps, schema):
    _Group = apps.get_model('auth', 'Group')
    _Permission = apps.get_model('auth', 'Permission')
    _ContentType = apps.get_model('contenttypes', 'ContentType')

    # driver permissions
    content_type, _ = _ContentType.objects.get_or_create(app_label='reservations', model='Bus')
    permission, _ = _Permission.objects.get_or_create(
        codename='can_drive', name='Can drive buses', content_type=content_type)
    group, _ = _Group.objects.get_or_create(name='driver')
    group.permissions.add(permission)

    # manager permissions
    content_type, _ = _ContentType.objects.get_or_create(app_label='users', model='User')
    permission, _ = _Permission.objects.get_or_create(
        codename='manager', name='Manager', content_type=content_type)
    group, _ = _Group.objects.get_or_create(name='manager')
    group.permissions.add(permission)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group_and_permissions)
    ]
